language: nix
script: ./ci.sh

addons:
  apt:
    packages:
      - xvfb
      - libgtk2.0-0
      - libnotify-dev
      - libgconf-2-4
      - libnss3
      - libxss1
      - libasound2

cache:
  npm: true
  directories:
    - /nix
    - ~/.cache
